### ISSUE TITLE
Icon background become grey when window is out of focus. 

### ISSUE THREAD

**Issue by danielos123ssa** [daniruiz/skeuos-gtk#19]
GTK 3.38, Ubuntu 20.04.
![Screenshot-20210715100539-410x795](https://user-images.githubusercontent.com/67702499/125737176-c5ebd7f2-d7f2-4fd3-90e3-8f84bee2e4a6.png)

It sometimes gets fixed after moving cursor over that window

**Comment by daniruiz** [comment]
The new update in github should fix this issue. It is caussed by NVIDIA GPUs (don't ask me why, it sounds random but it doesn't happen with MESA drivers :laughing: )
Tell me if it's fixed now

**Comment by danielos123ssa** [comment]
Downloaded latest master and installed both gnome 40 and 38 versions of shells + a few skeus color themes, issue still persists. :C

![Peek 2021-07-17 12-02](https://user-images.githubusercontent.com/67702499/126030592-74c6d549-76c2-421c-8e13-dc050bec238a.gif)

**Comment by daniruiz** [comment]
Oh cool, that video gave me a lot of information.
So it looks like the issue only happens when the window is not focus, is it? Then I can remove that background from the sidebar when it is not focus and the glitch wont be visible.
Thank you! :wink:

**Comment by danielos123ssa** [comment]
That's right, glad to be of help!

**Comment by daniruiz** [comment]
Pushed the new fix.
Try it and tell me if it is better now :pray:

**Comment by danielos123ssa** [comment]
Well, it took a slight design change, but it seems finally fixed! :D 
I like it more without the bar background anyway, makes it looks cleaner. Good job!

p.s you've been really nice, thank you.
